### ISSUE TITLE
Include tests with Buffer input

### ISSUE THREAD

**Issue by tmcw** [crypto-browserify/hash-test-vectors#2]
![2015-01-28 at 6 04 pm](https://cloud.githubusercontent.com/assets/32314/5949057/1ca540c6-a718-11e4-88ac-09a6c705411b.png)

Looks like this is something that's skipped in sub-tests - this should confirm that Buffer input as keys and `.update` inputs work.

**Comment by dominictarr** [comment]
is this issue ment to be about another module? this module only creates test data for other modules to use, it doesn't actually run any tests.

**Comment by tmcw** [comment]
Ah - you're right, the problem is downstream in createHmac.
